Bump provisioned dependencies
xamarin/Xamarin.PropertyEditing pull request #766
Opened 2021-04-08 15:39 UTC by BretJohnson

Bump provisioned dependencies to match what's currently used
for Designer, getting the latest Xamarin.Mac.

This is needed because the Xamarin.Mac.dll path changed and we
need to update the csproj reference to it accordingly, also done here.

2021-04-08 15:51 UTC, decriptor commented
I'm not sure why this built and worked, but things like this have to be changed:
https://github.com/xamarin/Xamarin.PropertyEditing/blob/1fd6c0b7f1221222bc93d0d509e267c64e19cb45/Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

- <MacFile Include="/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/x86_64/full/Xamarin.Mac.dll"/>
+ <MacFile Include="/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/64bits/full/Xamarin.Mac.dll"/>

2021-04-08 15:53 UTC, decriptor requested changes
See my other comment about the XamMac path

2021-04-08 15:58 UTC, BretJohnson commented
@decriptor Yeah, I meant to update that. Thx. Fixed.

2021-04-08 16:07 UTC, decriptor commented
@BretJohnson no worries. I've been dealing with it a bunch lately so it is on the top of my mind :) The other slightly older change was the location of libxammac.dylib, but I don't think it is referenced in here.

2021-04-08 16:46 UTC, BretJohnson commented
@mcumming And now the build fails, since the agent's installed VSMac doesn't have the latest Xamarin.Mac and we don't provision. Should we update to use different YAML, that does provisioning? Can you make that change?

2021-04-14 07:45 UTC, BretJohnson commented
@mcumming - ping on this

2021-04-30 17:10 UTC, decriptor commented
Closing in favor of #767

2021-04-30 17:10 UTC, closed without merging